version: "3.9"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - "6379:6379"
    networks:
      - app-network

  webapp:
    build: ../SampleAppForTesting/.
    image: flaskapp:latest
    container_name: webapp
    depends_on: 
      - redis
    ports: 
      - "5000:5000"
    networks:
      - app-network
    volumes: 
      - ./app:/app

networks:
  app-network:
